### ISSUE TITLE
If there are pictures in the pdf, they cannot be displayed.

### ISSUE THREAD

**Issue by rvnox** [anvithks/hugo-embed-pdf-shortcode#46]

**Comment by anvithks** [comment]
Hi @ayuxy Please share a link to your site repository. Please share your pdf file as well so that I can diagnose this issue.
Can you share a link to the website where site is rendered?

**Comment by ayuxy** [comment]
Hi，you can view [PDF Test](http://localhost:1313/posts/2023-1017-01/) and [PDF test2](http://localhost:1313/posts/2023-1017-02/) ，In PDF test1, the PDF can be displayed, but in PDF test2, the PDF cannot be displayed. Is this a network reason? Or because of the PDF content problem, I tested PDF test2 locally and could not display it. Even PDF test1 will load very slowly in most cases. I suspect that my PDF single-page file is too large.

**Comment by rvnox** [comment]
> Hi @ayuxy Please share a link to your site repository. Please share your pdf file as well so that I can diagnose this issue. Can you share a link to the website where site is rendered?

Hi，you can view [PDF Test](http://localhost:1313/posts/2023-1017-01/) and [PDF test2](http://localhost:1313/posts/2023-1017-02/) ，In PDF test1, the PDF can be displayed, but in PDF test2, the PDF cannot be displayed. Is this a network reason? Or because of the PDF content problem, I tested PDF test2 locally and could not display it. Even PDF test1 will load very slowly in most cases. I suspect that my PDF single-page file is too large.
