### ISSUE TITLE
Deploy pdf is not working

### ISSUE THREAD

**Issue by Dicky1** [anvithks/hugo-embed-pdf-shortcode#9]
sorry i reopened the issue. this time I get an error that the pdf does not appear again when deployed on netlify

![Screenshot_20210308_125753](https://user-images.githubusercontent.com/26633820/110280860-2430af80-800e-11eb-9558-e0c8391418e3.png)

**Comment by anvithks** [comment]
Please check the path of the file. It has to be inside the `content/` folder and the path should contain any subfolder that you use.
For ex: in your case, `{{< embed-pdf url="./post/LAPORAN_HASIL_MONITORING_KEAMANAN_SIBER_TAHUN_2020.pdf" >}}`
since your pdf file is inside the `post` folder. 
Try this and rebuild the website and clear your cache to check the site again.

**Comment by Dicky1** [comment]
try checking my repository, is it correct?

**Comment by anvithks** [comment]
Check my comment above and compare with your repository. let me know how it goes.

**Comment by anvithks** [comment]
looks like you fixed it.

**Comment by Dicky1** [comment]
I think it is in accordance with the comments above

[repository](https://github.com/Dicky1/hugo-blog/tree/main/content)

**Comment by anvithks** [comment]
This is your website.
I think the  pdf is taking time to load. 
![image](https://user-images.githubusercontent.com/19162717/110323126-26a8fe80-803a-11eb-80b5-54d2d8775ff1.png)

**Comment by Dicky1** [comment]
you try on local or my web hosting?

**Comment by anvithks** [comment]
> you try on local or my web hosting?

Open [this page](https://dickydiko.space/post/laporan-keamanan/)
leave it open for sometime (about 4.2 min)
The pdf loads after the entire document is downloaded.
I have raised an issue for adding a loader #10

**Comment by Dicky1** [comment]
yes we have to add a loader feature, in my computer loading (5.0 min)
